### ISSUE TITLE
Unparseable date: "2015-11-29T07:46:08Z"

### ISSUE THREAD

**Issue by slotties** [slotties/gw2trades#37]
java.text.ParseException: Unparseable date: "2015-11-29T07:46:08Z"
        at java.text.DateFormat.parse(DateFormat.java:366) ~[?:1.8.0_65]
        at gw2trades.repository.influxdb.InfluxDbRepository.lambda$getHistory$0(InfluxDbRepository.java:221) ~[repository-0.1-SNAPSHOT.jar!/:?]

is visible in the log sometimes. Usually the datapoints have a timestamp with msec-resolution yet this one is not. Weird.

**Comment by slotties** [comment]
doesn't happen anymore since I re-created the database.

**Comment by slotties** [comment]
happens again o_O

**Comment by slotties** [comment]
fixed

**Comment by slotties** [comment]
" Could not parse date string 2015-12-07T09:31:19.9Z"

again. fucking date formats. why are the msecs never 0-padded? ffs!

**Comment by slotties** [comment]
fixed. again. hopefully.
